### ISSUE TITLE
please exclude "und" from 10-20 values

### ISSUE THREAD

**Issue by ernestdolog** [chooklii/num-words-de#3]
**Describe the bug**
numToWord(14) -> Vierundzehn
numToWord(18) -> Achtundzehn

**To Reproduce**
14, 18 

**Expected behavior**
numToWord(14) -> Vierzehn
numToWord(18) -> Achtzehn

Maybe you could do this: const default_strings_len_one = ["Null", "eins", "zwei", "drei", "vier", "fünf", "sechs", "sieben", "acht", "neun", "zehn", "elf", "zwölf", "dreizehn", "vierzehn", "fünfzehn", "sechzehn", "siebzehn", "achtzehn", "neunzehn"]
and apply exceptions for 13-19 numbers too. They are exception i guess too.

**Comment by chooklii** [comment]
Hi @ernestdolog 

thanks for the report and sorry for the delay. The Bug is fixed with version 1.0.1
